### ISSUE TITLE
[PE-D][Tester B] Additional Tags not shown in the right order

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-1/tp#127]
![image.png](https://raw.githubusercontent.com/Charles1026/ped/main/files/0b126394-9a33-4adf-9253-79001cceec7a.png)

The first 5 tags shown are displayed from left to right, but the following additional tags are displayed from right to left.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Charles1026/ped#2

**Comment by nerbnerb** [comment]
Tags are displayed in lexicographical order, and the display of additional tags being reversed is indeed a bug. However, to display them in the order of addition would require a change to how tags are implemented, therefore this change (to display in order of addition) will not be added in v1.4.
