### ISSUE TITLE
[PE-D][Tester B] Date Applied can be set to any date 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-1/tp#137]
![image.png](https://raw.githubusercontent.com/Charles1026/ped/main/files/cbd738e4-07de-4261-a5a9-4ad8fc5db1a4.png)

Date applied should only be on or before the current date but it can be set to any date

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Charles1026/ped#6

**Comment by nerbnerb** [comment]
The user might want to apply, for example, the next day, but keep track of the application first by entering it today, therefore this functionality exists.
