### ISSUE TITLE
[PE-D][Tester B] Interview Dates accept all DateTimes

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-1/tp#144]
![image.png](https://raw.githubusercontent.com/Charles1026/ped/main/files/4a08b0a4-e924-4d6e-a37f-b5e971ceaa28.png)

Interview Dates should be on or after the current date and time but it can be set to anything.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Charles1026/ped#8

**Comment by desmondyst** [comment]
As a user, if I forget to add the Interview date/time, I may want to go back to add it so that I can keep track when I had the interview.
