### ISSUE TITLE
[PE-D][Tester D] Company link not fully visible for long inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-1/tp#145]
# Company link not fully visible for long inputs

Similar to the issue on the company name, because there is no character limit for the company link, if the company link happens to be extremely long, the company link would not be fully visible. However, because company URLs are not inherently meaningful (compared to company names) and presence of the copy link feature, this functionality bug is of very low severity

## Example

Command used: add c/TikTok l/https://a...a...a... /dGlobal e-Commerce a/11/10/2022 i/11/11/2022 15:00 t/Frontend (Left out most of the 'a' for readability)

Company Link Display:
![Output.png](https://raw.githubusercontent.com/kavantan/ped/main/files/5301aaaf-291d-4be7-aea6-cdf0e5c760c2.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: kavantan/ped#9

**Comment by Marcusgwj** [comment]
Not considered a bug. From Prof Damith: "_accommodating 'extreme' inputs (e.g., a person name with 1000 characters) can be considered a nice-to-have feature, to be added in a future version (i.e., lack of it is not a bug)._"
