### ISSUE TITLE
[PE-D][Tester B] No Word Cap for Company Name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-1/tp#146]
![image.png](https://raw.githubusercontent.com/Charles1026/ped/main/files/d0fdf2f3-ad61-4a6d-a095-c01dac49d20a.png)

Company name can be over 2k words long

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Charles1026/ped#9

**Comment by Marcusgwj** [comment]
Not considered a bug. From Prof Damith: _"accommodating 'extreme' inputs (e.g., a person name with 1000 characters) can be considered a nice-to-have feature, to be added in a future version (i.e., lack of it is not a bug)."_
