### ISSUE TITLE
[PE-D][Tester A] Date does not acept format (d MMM yyyy, h:mm a)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-1/tp#151]
Does not accept format as stated in UG e.g. 7/10/2022, 3:00 pm

![image.png](https://raw.githubusercontent.com/CedricChia123/ped/main/files/c9a6a25b-64ec-4d18-a57f-7c84980b478a.png)

![image.png](https://raw.githubusercontent.com/CedricChia123/ped/main/files/b063512c-31ed-47bd-9dcb-f8a7f0aaee1b.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: CedricChia123/ped#6

**Comment by desmondyst** [comment]
The exact format as stated in the UG is `d/M/yyyy, h:mm a`, and not `d/M/yyyy, h:mma`.

In other words, `7/10/2022, 3:00 pm` will work, and `7/10/2022, 3:00pm` will not work. 

In the screenshot above, it is `7/10/2022, 3:00pm`, thus the format is not accepted.
